[project]
name = "17-deploying-open-source-endpoints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.100.2",
    "together>=1.5.25",
    "langchain_community==0.3.0",
    "langchain_openai==0.2.0",
    "langchain-core==0.3.59",
    "langgraph>=0.2.0",
    "numpy==1.26.4",
    "tenacity==8.1.0",
    "pymupdf==1.24.10",
    "qdrant-client==1.11.2",
    "langchain_qdrant==0.1.4",
    "langsmith==0.1.125",
    "langchain_huggingface==0.2.0",
    "jupyter>=1.1.1",
    "tavily-python>=0.3.0",
    "arxiv>=2.1.0",
    "cryptography==44.0.3",
    "langchain-together>=0.2.0",
]
